export const htmlQues = [
  {
    quest: "What does HTML stand for?",
    opt1: "Hyper Text Markup Language",
    opt2: "High-Level Text Markup Language",
    opt3: "Home Tool Markup Language",
    opt4: "Hyperlink and Text Markup Language",
    correctAns: "opt1",
  },
  {
    quest: "Which HTML element is used to create a hyperlink?",
    opt1: "<link>",
    opt2: "<a>",
    opt3: "<href>",
    opt4: "<hyperlink>",
    correctAns: "opt2",
  },
  {
    quest: "What is the purpose of the HTML <head> element?",
    opt1: "To define the main content of the webpage",
    opt2: "To define the header of the webpage",
    opt3: "To contain metadata about the webpage",
    opt4: "To create a navigation menu",
    correctAns: "opt2",
  },
  {
    quest:
      "Which HTML tag is used to define the structure of an HTML document?",
    opt1: "<body>",
    opt2: "<header>",
    opt3: "<main>",
    opt4: "<html>",
    correctAns: "opt4",
  },
  {
    quest: "What is the correct way to comment out code in HTML?",
    opt1: "<!-- This is a comment -->",
    opt2: "// This is a comment //",
    opt3: "/* This is a comment */",
    opt4: "' This is a comment '",
    correctAns: "opt1",
  },
  {
    quest: "Which HTML tag is used to create an ordered list?",
    opt1: "<ol>",
    opt2: "<ul>",
    opt3: "<li>",
    opt4: "<list>",
    correctAns: "opt1",
  },
  {
    quest: "What is the purpose of the HTML <img> element?",
    opt1: "To create a link to another webpage",
    opt2: "To insert an image into a webpage",
    opt3: "To define a paragraph of text",
    opt4: "To create a table of data",
    correctAns: "opt2",
  },
  {
    quest:
      "Which attribute is used to specify the URL of an external stylesheet in HTML?",
    opt1: "src",
    opt2: "link",
    opt3: "style",
    opt4: "href",
    correctAns: "opt3",
  },
  {
    quest: "How do you create a line break in HTML?",
    opt1: "<lb>",
    opt2: "<break>",
    opt3: "<br>",
    opt4: "<newline>",
    correctAns: "opt3",
  },
  {
    quest: "What does HTML5 introduce for playing audio and video files?",
    opt1: "<audio> and <video> elements",
    opt2: "<media> element",
    opt3: "<sound> and <movie> elements",
    opt4: "<play> and <pause> elements",
    correctAns: "opt1",
  },
  {
    quest: "Which HTML tag is used to define a table row?",
    opt1: "<row>",
    opt2: "<tr>",
    opt3: "<td>",
    opt4: "<trow>",
    correctAns: "opt2",
  },
  {
    quest: "What is the purpose of the HTML <form> element?",
    opt1: "To create a list of options",
    opt2: "To define a section of a webpage",
    opt3: "To create a container for user input",
    opt4: "To display a message to the user",
    correctAns: "opt3",
  },
  {
    quest: "Which HTML attribute is used to specify the target of a hyperlink?",
    opt1: "target",
    opt2: "href",
    opt3: "link",
    opt4: "navigate",
    correctAns: "opt1",
  },
  {
    quest: "In HTML, which tag is used to define the header for a section or article?",
    opt1: "<header>",
    opt2: "<h1>",
    opt3: "<head>",
    opt4: "<section-header>",
    correctAns: "opt2",
  },
  {
    quest: "What is the correct way to include an external JavaScript file in an HTML document?",
    opt1: "<script src='script.js'></script>",
    opt2: "<js>script.js</js>",
    opt3: "<javascript src='script.js'></javascript>",
    opt4: "<external src='script.js'></external>",
    correctAns: "opt1",
  },
];
