export const htmlQues = [
  {
    quest: "What does HTML stand for?",
    opt1: "Hyper Text Markup Language",
    opt2: "High-Level Text Markup Language",
    opt3: "Home Tool Markup Language",
    opt4: "Hyperlink and Text Markup Language",
    correctAns: "opt1",
  },
  {
    quest: "Which HTML element is used to create a hyperlink?",
    opt1: "<link>",
    opt2: "<a>",
    opt3: "<href>",
    opt4: "<hyperlink>",
    correctAns: "opt2",
  },
  {
    quest: "What is the purpose of the HTML <head> element?",
    opt1: "To define the main content of the webpage",
    opt2: "To define the header of the webpage",
    opt3: "To contain metadata about the webpage",
    opt4: "To create a navigation menu",
    correctAns: "opt2",
  },
  {
    quest:
      "Which HTML tag is used to define the structure of an HTML document?",
    opt1: "<body>",
    opt2: "<header>",
    opt3: "<main>",
    opt4: "<html>",
    correctAns: "opt4",
  },
  {
    quest: "What is the correct way to comment out code in HTML?",
    opt1: "<!-- This is a comment -->",
    opt2: "// This is a comment //",
    opt3: "/* This is a comment */",
    opt4: "' This is a comment '",
    correctAns: "opt1",
  },
  {
    quest: "Which HTML tag is used to create an ordered list?",
    opt1: "<ol>",
    opt2: "<ul>",
    opt3: "<li>",
    opt4: "<list>",
    correctAns: "opt1",
  },
  {
    quest: "What is the purpose of the HTML <img> element?",
    opt1: "To create a link to another webpage",
    opt2: "To insert an image into a webpage",
    opt3: "To define a paragraph of text",
    opt4: "To create a table of data",
    correctAns: "opt2",
  },
  {
    quest:
      "Which attribute is used to specify the URL of an external stylesheet in HTML?",
    opt1: "src",
    opt2: "link",
    opt3: "style",
    opt4: "href",
    correctAns: "opt3",
  },
  {
    quest: "How do you create a line break in HTML?",
    opt1: "<lb>",
    opt2: "<break>",
    opt3: "<br>",
    opt4: "<newline>",
    correctAns: "opt3",
  },
  {
    quest: "What does HTML5 introduce for playing audio and video files?",
    opt1: "<audio> and <video> elements",
    opt2: "<media> element",
    opt3: "<sound> and <movie> elements",
    opt4: "<play> and <pause> elements",
    correctAns: "opt1",
  },
  {
    quest: "Which HTML tag is used to define a table row?",
    opt1: "<row>",
    opt2: "<tr>",
    opt3: "<td>",
    opt4: "<trow>",
    correctAns: "opt2",
  },
  {
    quest: "What is the purpose of the HTML <form> element?",
    opt1: "To create a list of options",
    opt2: "To define a section of a webpage",
    opt3: "To create a container for user input",
    opt4: "To display a message to the user",
    correctAns: "opt3",
  },
  {
    quest: "Which HTML attribute is used to specify the target of a hyperlink?",
    opt1: "target",
    opt2: "href",
    opt3: "link",
    opt4: "navigate",
    correctAns: "opt1",
  },
  {
    quest:
      "In HTML, which tag is used to define the header for a section or article?",
    opt1: "<header>",
    opt2: "<h1>",
    opt3: "<head>",
    opt4: "<section-header>",
    correctAns: "opt2",
  },
  {
    quest:
      "What is the correct way to include an external JavaScript file in an HTML document?",
    opt1: "<script src='script.js'></script>",
    opt2: "<js>script.js</js>",
    opt3: "<javascript src='script.js'></javascript>",
    opt4: "<external src='script.js'></external>",
    correctAns: "opt1",
  },
];
export const cssQuest = [
  {
    quest: "What does CSS stand for?",
    opt1: "Creative Style Sheets",
    opt2: "Cascading Style Sheets",
    opt3: "Colorful Style Sheets",
    opt4: "Computer Style Sheets",
    correctAns: "opt2",
  },
  {
    quest: "What is the correct HTML for referring to an external style sheet?",
    opt1: "<link rel='stylesheet' type='text/css' href='mystyle.css'>",
    opt2: "<style src='mystyle.css'>",
    opt3: "<m>mystyle.css</stylesheet>",
    opt4: "<myStyle>mystyle.css</myStyle>",
    correctAns: "opt1",
  },
  {
    quest:
      "What is the correct CSS syntax for making all the <span> elements bold?",
    opt1: "span {text-size: bold}",
    opt2: "span {font-weight: bold}",
    opt3: "<span style='font-size: bold'>",
    opt4: "<span style='text-size: bold'>",
    correctAns: "opt2",
  },
  {
    quest: "How do you add a comment in a CSS file?",
    opt1: "/* this is a comment */",
    opt2: "// this is a comment //",
    opt3: "// this is a comment",
    opt4: "<!-- this is a comment-->",
    correctAns: "opt1",
  },
  {
    quest: "What property is used to change the text color of an element?",
    opt1: "fontcolor:",
    opt2: "textcolor:",
    opt3: "color:",
    opt4: "font-color:",
    correctAns: "opt3",
  },
  {
    quest: "The # symbol specifies that the selector is?",
    opt1: "class",
    opt2: "tag",
    opt3: "first",
    opt4: "id",
    correctAns: "opt4",
  },
  {
    quest: "Which is the correct CSS syntax?",
    opt1: "{p:color=black(p}",
    opt2: "p {color: black;}",
    opt3: "{p;color:black}",
    opt4: "p:color=black",
    correctAns: "opt2",
  },
  {
    quest:
      "Which snippet of CSS is commonly used to center a website horizontally?",
    opt1: "site-align: center;",
    opt2: "margin: center;",
    opt3: "margin: auto 0;",
    opt4: "margin: 0 auto;",
    correctAns: "opt4",
  },
  {
    quest: "How do you make a list not display bullet points?",
    opt1: "list-style-type: no-bullet",
    opt2: "list: none",
    opt3: "bulletpoints: none",
    opt4: "list-style-type: none",
    correctAns: "opt4",
  },
  {
    quest: "What is the correct CSS syntax to change the font name?",
    opt1: "font-name:",
    opt2: "font:",
    opt3: "font-family:",
    opt4: "fontname:",
    correctAns: "opt3",
  },
  {
    quest: "What is the correct Syntax for importing a stylesheet in CSS?",
    opt1: "@import url(css/example.css);",
    opt2: "@import-stylesheet url(css/example.css);",
    opt3: "import-css url(css/example.css);",
    opt4: "@import-style url(css/example.css);",
    correctAns: "opt1",
  },
  {
    quest: "Which HTML attribute is used to define inline CSS styles?",
    opt1: "CSS",
    opt2: "Style",
    opt3: "ID",
    opt4: "Type",
    correctAns: "opt2",
  },
  {
    quest: "How do you make each word in a text start with a capital letter?",
    opt1: "text-transform: capitalize",
    opt2: "text-transform: uppercase",
    opt3: "You can't do that with CSS",
    opt4: "text: capitalize",
    correctAns: "opt4",
  },
  {
    quest: "A declaration is terminated by?",
    opt1: ". - period",
    opt2: "! - exclamation mark",
    opt3: "; - semi colon",
    opt4: ": - colon",
    correctAns: "opt3",
  },
  {
    quest: "Which CSS property controls the text size?",
    opt1: "font-height",
    opt2: "text-size",
    opt3: "font-size",
    opt4: "text-style",
    correctAns: "opt3",
  },
];

export const jsQuest = [
  {
    quest: "What is the result of 2 + 2?",
    opt1: "3",
    opt2: "4",
    opt3: "5",
    opt4: "6",
    correctAns: "opt2",
  },
  {
    quest: "How do you declare a variable in JavaScript?",
    opt1: "var myVar;",
    opt2: "variable myVar;",
    opt3: "let myVar;",
    opt4: "const myVar;",
    correctAns: "opt3",
  },
  {
    quest:
      "Which method is used to add an element to the end of an array in JavaScript?",
    opt1: "append()",
    opt2: "push()",
    opt3: "addToEnd()",
    opt4: "addElement()",
    correctAns: "opt2",
  },
  {
    quest: "What does the '===' operator do in JavaScript?",
    opt1: "Checks if two values are equal in value but not necessarily in type",
    opt2: "Checks if two values are equal in both value and type",
    opt3: "Assigns a value to a variable",
    opt4: "Checks if two values are not equal",
    correctAns: "opt2",
  },
  {
    quest: "What is the purpose of the 'if' statement in JavaScript?",
    opt1: "To loop through a block of code a specific number of times",
    opt2: "To define a function",
    opt3: "To execute a block of code only if a specified condition is true",
    opt4: "To declare a variable",
    correctAns: "opt3",
  },
  {
    quest:
      "Which built-in function is used to convert a string to an integer in JavaScript?",
    opt1: "parseInt()",
    opt2: "stringToInteger()",
    opt3: "toInteger()",
    opt4: "convertToInt()",
    correctAns: "opt1",
  },
  {
    quest:
      "What is the correct way to comment out a single line of code in JavaScript?",
    opt1: "// This is a comment",
    opt2: "/* This is a comment */",
    opt3: "<!-- This is a comment -->",
    opt4: "''' This is a comment '''",
    correctAns: "opt1",
  },
  {
    quest: "Which of the following is not a valid data type in JavaScript?",
    opt1: "number",
    opt2: "boolean",
    opt3: "undefined",
    opt4: "float",
    correctAns: "opt4",
  },
  {
    quest: "What is the purpose of the 'else' statement in JavaScript?",
    opt1: "To define a function",
    opt2: "To execute a block of code only if a specified condition is true",
    opt3: "To loop through a block of code a specific number of times",
    opt4: "To execute a block of code if the 'if' condition is false",
    correctAns: "opt4",
  },
  {
    quest:
      "Which method is used to remove the last element from an array in JavaScript?",
    opt1: "pop()",
    opt2: "remove()",
    opt3: "delete()",
    opt4: "splice()",
    correctAns: "opt1",
  },
  {
    quest: "What is the purpose of the 'for' loop in JavaScript?",
    opt1: "To define a function",
    opt2: "To execute a block of code only if a specified condition is true",
    opt3: "To iterate over a block of code a specific number of times",
    opt4: "To execute a block of code if the 'if' condition is false",
    correctAns: "opt3",
  },
  {
    quest:
      "Which JavaScript function is used to round a number to the nearest integer?",
    opt1: "ceil()",
    opt2: "round()",
    opt3: "floor()",
    opt4: "truncate()",
    correctAns: "opt2",
  },
  {
    quest: "What does the 'typeof' operator in JavaScript return for an array?",
    opt1: "array",
    opt2: "object",
    opt3: "list",
    opt4: "arraylist",
    correctAns: "opt2",
  },
  {
    quest:
      "Which built-in JavaScript function is used to find the length of an array?",
    opt1: "size()",
    opt2: "length()",
    opt3: "count()",
    opt4: "Array.length",
    correctAns: "opt4",
  },
  {
    quest: "What does the 'NaN' value represent in JavaScript?",
    opt1: "Not a Number",
    opt2: "Null and None",
    opt3: "Number and Null",
    opt4: "None of the above",
    correctAns: "opt1",
  },
];
